core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
# urls.py
from django.urls import path
from .views import HomeView, ProductListView, ProductDetailView, AuthorListView, AuthorDetailView, ProfileView, \
    AuthorLogoutView, CreateProductView, AuthorRegisterView, AuthorLoginView, ProductUpdateView, LikeAuthorView

app_name = 'market'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('explore/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='author_detail'),
    path('create/', CreateProductView.as_view(), name='create_product'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', AuthorLoginView.as_view(), name='login'),
    path('register/', AuthorRegisterView.as_view(), name='register'),
    path('logout/', AuthorLogoutView.as_view(), name='logout'),
    path('like_author/<pk>/', LikeAuthorView.as_view(), name='like_author'),
]

market/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CASCADE
from django.utils.translation import gettext_lazy as _


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Author(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='default_avatar.png')
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name=_('groups'),
        blank=True,
        help_text=_(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
        related_name="market_author_groups",
        related_query_name="market_author",
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name=_('user permissions'),
        blank=True,
        help_text=_('Specific permissions for this user.'),
        related_name="market_author_permissions",
        related_query_name="market_author",
    )

    class Meta:
        verbose_name_plural = "Authors"

    def __str__(self):
        return self.username

    @property
    def likes(self):
        return self.like_set.count()


class Product(AbstractBaseModel):
    PRODUCT_TYPE_CHOICES = (
        ('digital', 'Digital'),
        ('physical', 'Physical'),
        ('service', 'Service'),
        ('music', 'Music'),
        ('video', 'Video'),
        ('blockchain', 'Blockchain'),
        ('ai', 'Artificial Intelligence'),
        ('iot', 'Internet of Things'),
        ('other', 'Other'),
    )

    name = models.ForeignKey(Author, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.FileField(upload_to='products/', null=True, blank=True, default='default_product.png')
    ends_in = models.DateTimeField()  # renamed from 'ends_in'
    product_type = models.CharField(max_length=20, choices=PRODUCT_TYPE_CHOICES, default='other')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Products'
        db_table = 'products'


class AuthorLike(AbstractBaseModel):
    author = models.ForeignKey(Author, CASCADE, 'likes')

    class Meta:
        verbose_name_plural = 'Author Likes'
        db_table = 'author_likes'
        unique_together = ('author', 'created_at')

market/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import Form

from .models import Author, Product


class AuthorLoginForm(Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


class AuthorRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(max_length=28, widget=forms.TextInput(
        attrs={"id": "password", "type": "password"}))
    password2 = forms.CharField(max_length=28, widget=forms.TextInput(
        attrs={"id": "password", "type": "password"}))
    avatar = forms.FileField()

    def save(self, commit=True):
        user = super().save(commit)
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 == password2:
            user.set_password(password1)
            user.save()
        else:
            raise ValidationError("Passwords must be match")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

    class Meta:
        model = Author
        fields = ("username", "first_name", "last_name", "password1", "password2", "email", "avatar")


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'image', 'ends_in', 'product_type']
        widgets = {
            'ends_in': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'description': forms.Textarea(
                attrs={'rows': 5, 'cols': 20, 'class': 'form-control', 'placeholder': 'Description', 'required': True,
                       'autofocus': True, 'id': 'description'}),
            'product_type': forms.Select(attrs={'class': 'form-control'}),
        }


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'image', 'ends_in', 'product_type']
        widgets = {
            'ends_in': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'description': forms.Textarea(
                attrs={'rows': 5, 'cols': 20, 'class': 'form-control', 'placeholder': 'Description', 'required': True,
                       'autofocus': True, 'id': 'description'}),
            'product_type': forms.Select(attrs={'class': 'form-control'}),
        }


class ProductDetailForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'image', 'ends_in', 'product_type', 'name',]

market/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, View, CreateView
from django.contrib.auth import authenticate, login
from .forms import AuthorLoginForm, AuthorRegistrationForm, CreateProductForm
from .models import Product, Author, AuthorLike
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic.edit import FormView
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import UpdateView
from .forms import ProductUpdateForm
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from .models import Product
from .forms import ProductDetailForm
from django.http import JsonResponse
from django.views import View
from .models import Author
from django.shortcuts import render
from .models import Product



class HomeView(ListView):
    model = Product
    template_name = 'index.html'
    context_object_name = 'products'
    paginate_by = 10


class ProductListView(ListView):
    model = Product
    template_name = 'market/explore.html'
    context_object_name = 'products'
    paginate_by = 2

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #
    #     product_type = self.request.GET.get('product_type')
    #     title = self.request.GET.get('title')
    #     description = self.request.GET.get('description')
    #
    #     if product_type:
    #         queryset = queryset.filter(product_type=product_type)
    #     if title:
    #         queryset = queryset.filter(title__icontains=title)
    #     if description:
    #         queryset = queryset.filter(description__icontains=description)
    #
    #     return queryset


class AuthorListView(ListView):
    model = Author
    template_name = 'market/author.html'
    context_object_name = 'authors'
    paginate_by = 2

    def get_queryset(self):
        return Author.objects.all().exclude(id=self.request.user.id)


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'market/author.html'
    context_object_name = 'author'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(author=self.object)
        return context


class CreateProductView(CreateView):
    model = Product
    template_name = 'market/create.html'
    form_class = CreateProductForm

    def form_valid(self, form):
        product = form.save(commit=False)
        product.name = self.request.user  # Set the product's name to the currently logged-in user
        product.save()
        return redirect('market:profile')


class ProfileView(TemplateView):
    template_name = 'market/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.request.user  # If the User model is the Author model
        context['author'] = author
        context['products'] = Product.objects.filter(name_id=author.id)
        return context


class AuthorRegisterView(FormView):
    form_class = AuthorRegistrationForm
    template_name = 'register.html'
    success_url = reverse_lazy('market:login')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "User successfully registered")
        return super().form_valid(form)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {"form": form})


class AuthorLoginView(View):
    def get(self, request):
        form = AuthorLoginForm()
        return render(request, "login.html", context={"form": form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You have logged in as {username}")
                return redirect("market:home")
            else:
                messages.error(request, "Invalid username or password")
        else:
            return render(request, "login.html", {"form": form})


class AuthorLogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "User successfully loged out")
        return redirect("market:home")


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductUpdateForm
    template_name = 'market/product_update.html'  # Specify your own template name/path

    def get_success_url(self):
        return reverse('market:product_detail', kwargs={'pk': self.object.pk})


class ProductDetailView(FormMixin, DetailView):
    model = Product
    template_name = 'market/details.html'
    context_object_name = 'product'
    form_class = ProductDetailForm

    def get_success_url(self):
        return reverse('market:product_detail', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class LikeAuthorView(LoginRequiredMixin, View):
    def get(self, request, pk):
        product = Product.objects.get(pk=pk)
        like, created = AuthorLike.objects.get_or_create(author_id=request.user.id, product=product)
        if not created:
            like.delete()
        return redirect(reverse("market:author_detail", kwargs={"pk": product.pk}))




def explore(request):
    title = request.GET.get('title', '')
    product_type = request.GET.get('product_type', '')

    products = Product.objects.all()

    if title:
        products = products.filter(title__icontains=title)
        print(f"Searching for products with title '{title}'")
        print(f"Found {products.count()} products")

    if product_type and product_type != 'All Types':
        products = products.filter(product_type=product_type)

    return render(request, 'explore.html', {'products': products})

templates/market/author.html
{% extends 'base.html' %}
{% block title %}Author Details{% endblock %}
{% block content %}
    {% load static %}
    <div class="page-heading normal-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6>Author Details</h6>
                    <h2>View Details For Author</h2>
                    <span>Home > <a href="{% url 'market:home' %}">Author</a></span>
                    <div class="buttons">
                        <div class="main-button">
                            <a href="{% url 'market:product_list' %}">Explore Our Items</a>
                        </div>
                        <div class="border-button">
                            <a href="{% url 'market:create_product' %}">Create Your NFT</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 <div class="author-page">
<div class="container">
  <div class="row">
      {% for author in authors %}
    <div class="col-lg-6">
      <div class="author">
        {% if author.avatar %}
          <img src="{{ author.avatar.url }}" alt="" style="border-radius: 50%; max-width: 170px;">
        {% else %}
        {% endif %}
          <img src="{% static 'default-avatar.png' %}" alt="" style="border-radius: 50%; max-width: 170px;">
        <h4>{{ author.first_name }} {{ author.last_name }}<br> <a href="#">@{{ author.username }}</a></h4>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="right-info">
        <div class="row">
          <div class="col-4">
            <div class="info-item">
              <i class="fa fa-heart"></i>
              <h6>{{ author.like_count }}<em>Likes</em></h6>
            </div>
          </div>
          <div class="col-4">
            <div class="info-item">
              <i class="fa fa-hand"></i>
              <h6>{{ author.like_count }} <em>Likes</em></h6>
            </div>
          </div>
          <div class="col-4">
            <div class="info-item">
              <i class="fa fa-dollar"></i>
              <h6>{{ author.like_count }} <em>Likes</em></h6>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-5">
            <h5>559 Followers</h5>
          </div>
          <div class="col-7">
            <div class="main-button">
              <a href="{% url 'market:like_author' author.pk %}">Like Button @{{ author.username }}</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  {% include 'market/author_pagination.html' %}
  </div>
</div>
</div>

    {#    FOOOOTEEEER#}
    <div class="create-nft">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>Create Your NFT & Put It On The Market.</h2>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="main-button">
                        <a href="{% url 'market:create_product' %}">Create Your NFT Now</a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item first-item">
                        <div class="number">
                            <h6>1</h6>
                        </div>
                        <div class="icon">
                            <img src="{% static 'assets/images/icon-02.png' %}" alt="">
                        </div>
                        <h4>Set Up Your Wallet</h4>
                        <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item second-item">
                        <div class="number">
                            <h6>2</h6>
                        </div>
                        <div class="icon">
                            <img src="{% static 'assets/images/icon-04.png' %}" alt="">
                        </div>
                        <h4>Add Your Digital NFT</h4>
                        <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item">
                        <div class="icon">
                            <img src="{% static 'assets/images/icon-06.png' %}" alt="">
                        </div>
                        <h4>Sell Your NFT &amp; Make Profit</h4>
                        <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/market/author_pagination.html
<div class="row">
    <div class="col-6">
        {% if  page_obj.has_previous %}
            <a href="?page=1">    First Page    </a>
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
        {{ page_obj.number }}
        {% if  page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">   Last Page   </a>
        {% endif %}
    </div>
    <div class="col-3">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                    aria-expanded="false">
                Page Size
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="?size=5">5</a>
                <a class="dropdown-item" href="?size=10">10</a>
                <a class="dropdown-item" href="?size=20">20</a>
            </div>
        </div>
    </div>
</div>

templates/market/create.html
{% extends 'base.html' %}
{% block title %}Create Yours{% endblock %}
{% load static %}
{% block content %}

  <div class="page-heading normal-space">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>Liberty NFT Market</h6>
          <h2>Create Your NFT Now.</h2>
          <span>Home > <a href="#">Create Yours</a></span>
          <div class="buttons">
            <div class="main-button">
              <a href="{% url 'market:product_list' %}">Explore Our Items</a>
            </div>
            <div class="border-button">
              <a href="{% url 'market:create_product' %}">Create Your NFT</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="item-details-page">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>Apply For <em>Your Item</em> Here.</h2>
          </div>
        </div>
        <div class="col-lg-12">
          <form id="contact" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" id="form-submit" class="orange-button">Submit Your Applying</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/market/details.html
{% extends 'base.html' %}
{% block title %}Details{% endblock %}
{% load static %}
{% block content %}

    <div class="page-heading normal-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6>Liberty NFT Market</h6>
                    <h2>View Item Details</h2>
                    <span>Home > <a href="#">Item Details</a></span>
                    <div class="buttons">
                        <div class="main-button">
                            <a href="{% url 'market:product_list' %}">Explore Our Items</a>
                        </div>
                        <div class="border-button">
                            <a href="{% url 'market:create_product' %}">Create Your NFT</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="item-details-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>View Details <em>For Item</em> Here.</h2>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="left-image">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}" style="max-width: 400px; border-radius: 10%;">
                    </div>
                </div>
                <div class="col-lg-5 align-self-center">
                    <h4>{{ product.title }}</h4>
                    <span class="author">
                        <img src="{{ product.name.avatar.url }}" alt="{{ product.name.first_name }}" style="max-width: 50px; border-radius: 50%;">
                        <h6>{{ product.name.first_name }} {{ product.name.last_name }}<br><a href="#">@{{ product.name.username }}</a></h6>
                    </span>
                    <p>{{ product.description }}</p>
                    <div class="row">
                        <div class="col-3">
                            <span class="bid">
                                Current Bid<br><strong>{{ product.price }} $</strong><br><em></em>
                            </span>
                        </div>
                        <div class="col-5">
                            <span class="ends">
                                Ends In<br><strong>{{ product.ends_in }}</strong><br><em>{{ product.end_date }}</em>
                            </span>
                        </div>
                    </div>
                    <form method="post" action="{% url 'market:product_detail' product.id %}">
                        {% csrf_token %}
                        <label for="quantity-text">Place Bid:</label>
                        <input placeholder="{{ product.price }} $" class="quantity-text" name="bid">
                        <button type="submit" id="form-submit" class="main-button">Submit Now</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="create-nft">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>Create Your NFT & Put It On The Market.</h2>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="main-button">
                        <a href="{% url 'market:create_product' %}">Create Your NFT Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/market/product_pagination.html
<div class="row">
    <div class="col-6">
        {% if  page_obj.has_previous %}
            <a href="?page=1">    First Page    </a>
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
        {{ page_obj.number }}
        {% if  page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">   Last Page   </a>
        {% endif %}
    </div>
    <div class="col-3">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                    aria-expanded="false">
                Page Size
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="?size=5">5</a>
                <a class="dropdown-item" href="?size=10">10</a>
                <a class="dropdown-item" href="?size=20">20</a>
            </div>
        </div>
    </div>
</div>

templates/market/product_update.html
{% extends 'base.html' %}
{% block title %}Create Yours{% endblock %}
{% load static %}
{% block content %}

  <div class="page-heading normal-space">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>Liberty NFT Market</h6>
          <h2>Update Your NFT Now.</h2>
          <span>Home > <a href="#">Update</a></span>
          <div class="buttons">
            <div class="main-button">
              <a href="{% url 'market:product_list' %}">Explore Our Items</a>
            </div>
            <div class="border-button">
              <a href="{% url 'market:create_product' %}">Update Your NFT</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="item-details-page">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2> Update <em>Your Item</em> Here.</h2>
          </div>
        </div>
        <div class="col-lg-12">
          <form id="contact" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" id="form-submit" class="orange-button">Submit Your Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/market/profile.html
{% extends 'base.html' %}
{% block title %}Author Details{% endblock %}
{% block content %}
    {% load static %}

    <div class="author-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="author">
                        <img src="{{ author.avatar.url }}" alt="" style="border-radius: 50%; max-width: 170px;">
                        <h4>{{ author.first_name }} {{ author.last_name }} <br> <a href="#">@{{ author.username }}</a>
                        </h4>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="right-info">
                        <div class="row">
                            <div class="col-4">
                                <div class="info-item">
                                    <i class="fa fa-heart"></i>
                                    <h6>{{ author.likes }} <em>Likes</em></h6>
                                    {# Assuming the Author model has a 'likes' field #}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {# My Items #}
                <div class="col-lg-12">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>My <em>Items</em>.</h2>
                    </div>
                </div>
                {% for product in products %}
                    <div class="col-lg-3 col-md-6">
                        <div class="item">
                            <div class="row">
                                <div class="col-lg-12">
        <span class="author">
          <img src="{{ author.avatar.url }}" alt="" style="max-width: 50px; border-radius: 50%;">
        </span>
                                    <img src="{{ product.image.url }}" alt="" style="border-radius: 20px;">
                                    {# Assuming the Product model has an 'image' field #}
                                    <h4>{{ product.title }}</h4>
                                    <a href="{% url 'market:product_detail' product.id %}" class="btn btn-primary">View
                                        detail</a> {# Ensure you're passing the product's id #}
                                    <a href="{% url 'market:product_update' product.id %}" class="btn btn-secondary">Update</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}